name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
        django-version: ['2.2', '3.0', '3.1', '3.2']
        include:
          - python-version: '2.7'
            django-version: '1.11'
          - python-version: '3.6'
            django-version: '1.11'
          - python-version: '3.6'
            django-version: '2.0'
          - python-version: '3.6'
            django-version: '2.1'
          - python-version: '3.7'
            django-version: '2.0'
          - python-version: '3.7'
            django-version: '2.1'
          - python-version: '3.10'
            django-version: '3.2'
          - python-version: '3.8'
            django-version: '4.0'
          - python-version: '3.9'
            django-version: '4.0'
          - python-version: '3.10'
            django-version: '4.0'
          - python-version: '3.8'
            django-version: '4.1'
          - python-version: '3.9'
            django-version: '4.1'
          - python-version: '3.10'
            django-version: '4.1'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/ci.txt
          pip install -q Django==${{ matrix.django-version }}
      - name: Run Tests
        run: |
          coverage run --source request_signer manage.py test
          coverage report --show-missing
          flake8 request_signer --max-line-length=120 --max-complexity=5
